"""Recipe corpus for Pantry to Plan.

40 lunch/dinner recipes, 10 per cuisine (italian, american, chinese, indian),
with at least 4 vegetarian recipes per cuisine so a 3-5 day all-vegetarian plan
is possible even within a single cuisine.

Conventions (see schemas.py):
- ingredient ids are lowercase snake_case and shared across recipes so they
  join cleanly against pantry state and the shopping list
- ingredient quantities are grams needed for one serving
- calories are per serving (one recipe == one day's dinner in the demo)
- cuisine_tags holds a single tag here, but the field is a list to allow
  fusion/multi-tag recipes later
- instructions are a short ordered list of steps, kept concise on purpose;
  they are the source of truth for the UI drilldown and are deliberately NOT
  part of the retrieval/embedding text (see index_recipes.recipe_text)
"""

from schemas import Recipe, RecipeIngredient


def _r(recipe_id, title, cuisine, calories, vegetarian, ingredients, instructions):
    """Build a Recipe from a compact (single-cuisine, dict-ingredients) spec."""
    return Recipe(
        recipe_id=recipe_id,
        title=title,
        cuisine_tags=[cuisine],
        calories_per_serving=calories,
        vegetarian=vegetarian,
        ingredients=[
            RecipeIngredient(ingredient_id=k, quantity_g=v)
            for k, v in ingredients.items()
        ],
        instructions=instructions,
    )


RECIPES: list[Recipe] = [
    # ---------------------------------------------------------------- italian
    _r("it_aglio_e_olio", "Spaghetti Aglio e Olio", "italian", 520, True,
       {"spaghetti": 110, "olive_oil": 30, "garlic": 15,
        "red_pepper_flakes": 2, "parsley": 8},
       ["Boil the spaghetti until al dente.",
        "Gently warm the olive oil with sliced garlic and red pepper flakes.",
        "Toss the drained pasta with the oil and parsley, season, and serve."]),
    _r("it_margherita_flatbread", "Margherita Flatbread", "italian", 610, True,
       {"pizza_dough": 200, "tomato_sauce": 90, "mozzarella": 100,
        "basil": 6, "olive_oil": 12},
       ["Stretch the pizza dough onto a tray.",
        "Spread with tomato sauce and top with mozzarella.",
        "Bake until bubbling, then finish with basil and a drizzle of olive oil."]),
    _r("it_penne_arrabbiata", "Penne Arrabbiata", "italian", 540, True,
       {"penne": 110, "canned_tomatoes": 200, "garlic": 12,
        "red_pepper_flakes": 3, "olive_oil": 20, "parsley": 6},
       ["Boil the penne until al dente.",
        "Simmer canned tomatoes with garlic, red pepper flakes, and olive oil.",
        "Toss the sauce with the pasta and parsley and serve."]),
    _r("it_mushroom_risotto", "Mushroom Risotto", "italian", 580, True,
       {"arborio_rice": 90, "mushroom": 150, "onion": 60, "parmesan": 30,
        "vegetable_broth": 400, "butter": 20, "white_wine": 40},
       ["Saute the onion and mushrooms in butter.",
        "Add the rice and white wine, then ladle in warm broth, stirring until creamy.",
        "Stir in the parmesan and serve."]),
    _r("it_caprese_farro_salad", "Caprese Farro Salad", "italian", 470, True,
       {"farro": 80, "tomato": 120, "mozzarella": 80, "basil": 6,
        "olive_oil": 18, "balsamic_vinegar": 10},
       ["Cook the farro until tender, then cool.",
        "Toss with tomato, mozzarella, and basil.",
        "Dress with olive oil and balsamic and serve."]),
    _r("it_tuscan_white_bean_soup", "Tuscan White Bean Soup", "italian", 430, True,
       {"cannellini_beans": 200, "kale": 80, "onion": 70, "garlic": 10,
        "carrot": 60, "vegetable_broth": 400, "olive_oil": 15},
       ["Saute the onion, carrot, and garlic in olive oil.",
        "Add the beans and broth and simmer.",
        "Stir in the kale until wilted, season, and serve."]),
    _r("it_chicken_parmesan", "Chicken Parmesan", "italian", 720, False,
       {"chicken_breast": 180, "breadcrumbs": 40, "egg": 50, "tomato_sauce": 120,
        "mozzarella": 60, "parmesan": 20, "olive_oil": 20},
       ["Bread the chicken in egg and breadcrumbs, then pan-fry in olive oil.",
        "Top with tomato sauce, mozzarella, and parmesan.",
        "Bake until melted and cooked through."]),
    _r("it_spaghetti_bolognese", "Spaghetti Bolognese", "italian", 680, False,
       {"spaghetti": 110, "ground_beef": 150, "canned_tomatoes": 200,
        "onion": 60, "garlic": 10, "carrot": 50, "olive_oil": 15},
       ["Brown the ground beef with onion, garlic, and carrot in olive oil.",
        "Add canned tomatoes and simmer into a sauce.",
        "Toss with boiled spaghetti and serve."]),
    _r("it_shrimp_scampi_linguine", "Shrimp Scampi Linguine", "italian", 590, False,
       {"linguine": 110, "shrimp": 140, "garlic": 15, "butter": 25,
        "white_wine": 50, "parsley": 6, "lemon": 30},
       ["Boil the linguine until al dente.",
        "Saute garlic in butter, add shrimp and white wine, and cook until pink.",
        "Toss with the pasta, parsley, and lemon."]),
    _r("it_prosciutto_arugula_pizza", "Prosciutto and Arugula Pizza", "italian", 700, False,
       {"pizza_dough": 200, "mozzarella": 100, "prosciutto": 50, "arugula": 30,
        "olive_oil": 12, "parmesan": 15},
       ["Bake the mozzarella-topped dough brushed with olive oil.",
        "Top the hot crust with prosciutto and arugula.",
        "Finish with parmesan and serve."]),
    # --------------------------------------------------------------- american
    _r("am_grilled_cheese_tomato_soup", "Grilled Cheese and Tomato Soup", "american", 560, True,
       {"bread": 90, "cheddar": 60, "butter": 20, "canned_tomatoes": 200,
        "onion": 50, "vegetable_broth": 250},
       ["Simmer canned tomatoes, onion, and broth, then blend smooth.",
        "Butter the bread and grill with cheddar until golden.",
        "Serve the sandwich alongside the soup."]),
    _r("am_mac_and_cheese", "Baked Mac and Cheese", "american", 650, True,
       {"macaroni": 120, "cheddar": 90, "milk": 150, "butter": 20,
        "flour": 15, "breadcrumbs": 25},
       ["Cook the macaroni.",
        "Make a roux with butter, flour, and milk, then melt in the cheddar.",
        "Combine, top with breadcrumbs, and bake until bubbly."]),
    _r("am_black_bean_burger", "Black Bean Burger", "american", 540, True,
       {"black_beans": 160, "burger_bun": 80, "breadcrumbs": 30, "onion": 40,
        "corn": 50, "cheddar": 30},
       ["Mash black beans with corn, onion, and breadcrumbs and form patties.",
        "Pan-fry the patties until crisp.",
        "Serve on buns with cheddar."]),
    _r("am_buffalo_cauliflower_bowl", "Buffalo Cauliflower Bowl", "american", 480, True,
       {"cauliflower": 200, "hot_sauce": 30, "rice": 150, "black_beans": 100,
        "avocado": 60, "ranch_dressing": 25},
       ["Roast the cauliflower and toss in hot sauce.",
        "Cook the rice.",
        "Build bowls with rice, black beans, cauliflower, avocado, and ranch."]),
    _r("am_loaded_baked_potato", "Loaded Baked Potato", "american", 500, True,
       {"potato": 280, "cheddar": 50, "sour_cream": 40, "butter": 15,
        "broccoli": 80, "green_onion": 15},
       ["Bake the potato until tender.",
        "Steam the broccoli.",
        "Split and top with cheddar, sour cream, butter, and green onion."]),
    _r("am_veggie_quesadilla", "Veggie Quesadilla", "american", 520, True,
       {"tortilla": 100, "cheddar": 70, "bell_pepper": 70, "onion": 40,
        "corn": 50, "black_beans": 80},
       ["Saute the bell pepper, onion, corn, and black beans.",
        "Fill the tortilla with the vegetables and cheddar.",
        "Griddle until golden and the cheese melts, then slice."]),
    _r("am_classic_cheeseburger", "Classic Cheeseburger", "american", 700, False,
       {"ground_beef": 150, "burger_bun": 80, "cheddar": 40, "lettuce": 20,
        "tomato": 40, "onion": 30},
       ["Form and grill the beef patties, melting cheddar on top.",
        "Toast the buns.",
        "Assemble with lettuce, tomato, and onion."]),
    _r("am_bbq_pulled_chicken_sandwich", "BBQ Pulled Chicken Sandwich", "american", 610, False,
       {"chicken_breast": 160, "bbq_sauce": 45, "burger_bun": 80,
        "coleslaw_mix": 60, "onion": 30},
       ["Simmer and shred the chicken, then toss with bbq sauce.",
        "Pile onto the buns.",
        "Top with coleslaw mix and onion."]),
    _r("am_cobb_salad", "Cobb Salad", "american", 560, False,
       {"romaine_lettuce": 120, "chicken_breast": 120, "bacon": 30, "egg": 50,
        "avocado": 60, "blue_cheese": 30, "tomato": 60},
       ["Cook and slice the chicken, bacon, and egg.",
        "Arrange over romaine with avocado, tomato, and blue cheese.",
        "Dress and serve."]),
    _r("am_maple_glazed_salmon", "Maple Glazed Salmon", "american", 590, False,
       {"salmon": 180, "maple_syrup": 25, "soy_sauce": 15, "broccoli": 120,
        "rice": 150, "garlic": 8},
       ["Glaze the salmon with maple syrup and soy sauce and roast.",
        "Steam the broccoli and cook the rice.",
        "Plate together with the garlic."]),
    # ---------------------------------------------------------------- chinese
    _r("cn_vegetable_fried_rice", "Vegetable Fried Rice", "chinese", 480, True,
       {"rice": 180, "egg": 50, "peas": 50, "carrot": 50, "green_onion": 15,
        "soy_sauce": 20, "sesame_oil": 10},
       ["Scramble the egg and set aside.",
        "Stir-fry the peas, carrot, and green onion, then add the rice.",
        "Toss with the egg, soy sauce, and sesame oil."]),
    _r("cn_kung_pao_tofu", "Kung Pao Tofu", "chinese", 520, True,
       {"tofu": 200, "peanuts": 30, "bell_pepper": 70, "green_onion": 15,
        "soy_sauce": 20, "garlic": 10, "dried_chili": 3, "rice": 150},
       ["Pan-fry the tofu until golden.",
        "Stir-fry the bell pepper, garlic, green onion, and dried chili.",
        "Toss with the tofu, soy sauce, and peanuts; serve over rice."]),
    _r("cn_mapo_tofu", "Mapo Tofu", "chinese", 560, False,
       {"tofu": 220, "ground_pork": 90, "doubanjiang": 25, "green_onion": 15,
        "garlic": 10, "ginger": 8, "rice": 150, "sichuan_peppercorn": 2},
       ["Brown the ground pork with doubanjiang, garlic, and ginger.",
        "Add the tofu and simmer.",
        "Finish with green onion and Sichuan peppercorn; serve over rice."]),
    _r("cn_broccoli_garlic_stir_fry", "Garlic Broccoli Stir Fry", "chinese", 410, True,
       {"broccoli": 200, "garlic": 15, "soy_sauce": 20, "sesame_oil": 10,
        "rice": 150, "ginger": 8},
       ["Blanch the broccoli.",
        "Stir-fry with the garlic and ginger.",
        "Season with soy sauce and sesame oil; serve over rice."]),
    _r("cn_egg_drop_noodle_soup", "Egg Drop Noodle Soup", "chinese", 440, True,
       {"egg": 100, "vegetable_broth": 400, "green_onion": 15, "ginger": 8,
        "noodles": 90, "soy_sauce": 15},
       ["Simmer the broth with ginger.",
        "Cook the noodles in it, then swirl in the beaten egg.",
        "Finish with green onion and soy sauce."]),
    _r("cn_kung_pao_chicken", "Kung Pao Chicken", "chinese", 610, False,
       {"chicken_breast": 170, "peanuts": 30, "bell_pepper": 70, "green_onion": 15,
        "soy_sauce": 20, "dried_chili": 3, "garlic": 10, "rice": 150},
       ["Stir-fry the diced chicken until cooked.",
        "Add the bell pepper, garlic, green onion, and dried chili.",
        "Toss with soy sauce and peanuts; serve over rice."]),
    _r("cn_beef_and_broccoli", "Beef and Broccoli", "chinese", 640, False,
       {"flank_steak": 170, "broccoli": 150, "soy_sauce": 25, "garlic": 10,
        "ginger": 8, "rice": 150, "oyster_sauce": 20},
       ["Sear the sliced flank steak.",
        "Stir-fry the broccoli with garlic and ginger.",
        "Toss with soy and oyster sauce; serve over rice."]),
    _r("cn_sweet_and_sour_pork", "Sweet and Sour Pork", "chinese", 680, False,
       {"pork": 170, "pineapple": 80, "bell_pepper": 70, "onion": 50,
        "ketchup": 40, "rice": 150, "cornstarch": 20},
       ["Coat the pork in cornstarch and fry until crisp.",
        "Stir-fry the bell pepper, onion, and pineapple.",
        "Toss in a ketchup sweet-and-sour sauce; serve over rice."]),
    _r("cn_shrimp_lo_mein", "Shrimp Lo Mein", "chinese", 560, False,
       {"shrimp": 140, "lo_mein_noodles": 130, "cabbage": 80, "carrot": 50,
        "soy_sauce": 25, "sesame_oil": 10, "green_onion": 15},
       ["Boil the lo mein noodles.",
        "Stir-fry the shrimp, cabbage, carrot, and green onion.",
        "Toss with the noodles, soy sauce, and sesame oil."]),
    _r("cn_general_tso_chicken", "General Tso's Chicken", "chinese", 700, False,
       {"chicken_thigh": 180, "soy_sauce": 25, "hoisin_sauce": 30, "garlic": 10,
        "rice": 150, "broccoli": 80, "cornstarch": 20},
       ["Coat the chicken in cornstarch and fry.",
        "Make a sauce of soy sauce, hoisin, and garlic.",
        "Toss the chicken and broccoli in the sauce; serve over rice."]),
    # ----------------------------------------------------------------- indian
    _r("in_chana_masala", "Chana Masala", "indian", 520, True,
       {"chickpeas": 200, "onion": 70, "tomato": 120, "garlic": 10, "ginger": 8,
        "garam_masala": 6, "rice": 150},
       ["Saute the onion, garlic, and ginger.",
        "Add tomato and garam masala and cook down.",
        "Simmer the chickpeas in the sauce; serve over rice."]),
    _r("in_palak_paneer", "Palak Paneer", "indian", 560, True,
       {"paneer": 150, "spinach": 200, "onion": 60, "tomato": 80, "garlic": 10,
        "ginger": 8, "garam_masala": 6},
       ["Blanch and blend the spinach.",
        "Saute onion, garlic, ginger, and tomato with garam masala.",
        "Stir in the spinach and paneer and simmer."]),
    _r("in_dal_tadka", "Dal Tadka", "indian", 470, True,
       {"red_lentils": 150, "onion": 60, "tomato": 90, "garlic": 10, "cumin": 4,
        "turmeric": 3, "rice": 150},
       ["Simmer the red lentils with turmeric until soft.",
        "Temper cumin, onion, garlic, and tomato in oil.",
        "Stir the tempering into the dal; serve over rice."]),
    _r("in_aloo_gobi", "Aloo Gobi", "indian", 440, True,
       {"potato": 180, "cauliflower": 180, "onion": 60, "tomato": 80,
        "turmeric": 3, "cumin": 4, "peas": 50},
       ["Saute the onion with cumin and turmeric.",
        "Add the potato, cauliflower, and tomato.",
        "Cover and cook until tender, then stir in the peas."]),
    _r("in_vegetable_biryani", "Vegetable Biryani", "indian", 590, True,
       {"basmati_rice": 180, "carrot": 60, "peas": 60, "onion": 70, "yogurt": 60,
        "garam_masala": 6, "cashews": 20},
       ["Saute the onion, carrot, and peas with garam masala.",
        "Layer with parboiled basmati rice and yogurt.",
        "Steam covered and top with cashews."]),
    _r("in_paneer_tikka_wrap", "Paneer Tikka Wrap", "indian", 540, True,
       {"paneer": 140, "tortilla": 90, "yogurt": 50, "onion": 50,
        "bell_pepper": 60, "garam_masala": 5},
       ["Marinate the paneer in yogurt and garam masala, then sear with bell pepper and onion.",
        "Warm the tortilla.",
        "Wrap the filling and serve."]),
    _r("in_chicken_tikka_masala", "Chicken Tikka Masala", "indian", 650, False,
       {"chicken_breast": 180, "yogurt": 60, "tomato": 120, "onion": 70,
        "garlic": 10, "ginger": 8, "garam_masala": 6, "rice": 150},
       ["Marinate the chicken in yogurt and garam masala, then sear.",
        "Simmer onion, tomato, garlic, and ginger into a sauce.",
        "Add the chicken and simmer; serve over rice."]),
    _r("in_butter_chicken", "Butter Chicken", "indian", 720, False,
       {"chicken_thigh": 180, "butter": 25, "tomato": 120, "cream": 50,
        "onion": 60, "garam_masala": 6, "rice": 150},
       ["Sear the chicken thigh.",
        "Simmer tomato, onion, garam masala, butter, and cream into a sauce.",
        "Add the chicken and simmer; serve over rice."]),
    _r("in_lamb_rogan_josh", "Lamb Rogan Josh", "indian", 690, False,
       {"lamb": 180, "yogurt": 60, "onion": 70, "tomato": 100, "garlic": 10,
        "ginger": 8, "garam_masala": 7, "rice": 150},
       ["Brown the lamb.",
        "Cook onion, garlic, ginger, tomato, and garam masala.",
        "Add yogurt and braise until tender; serve over rice."]),
    _r("in_fish_curry", "South Indian Fish Curry", "indian", 560, False,
       {"white_fish": 180, "coconut_milk": 120, "onion": 60, "tomato": 90,
        "turmeric": 3, "curry_leaves": 2, "rice": 150},
       ["Saute onion and tomato with turmeric and curry leaves.",
        "Add the coconut milk and simmer.",
        "Poach the white fish in the sauce; serve over rice."]),
]
